export const ACTION_TYPE = {
	LOADING_START: 'LOADING_START',
	LOADING_END: 'LOADING_END',
	SET_TODOS: 'SET_TODOS',
	SET_SEARCH: 'SET_SEARCH',
	SET_ORDER_BY: 'SET_ORDER_BY',
	ADD_TODO: 'ADD_TODO',
	UPDATE_TODO: 'UPDATE_TODO',
	REMOVE_TODO: 'REMOVE_TODO',
	EDIT_TODO: 'EDIT_TODO',
};
